package org.k8scmp.model;

public enum ServiceStatus {
    DELETED, RUNNING, STOP, ERROR, DEPLOYING, STOPPING, UPDATING, UPSCALING, DOWNSCALING, BACKROLLING, ABORTING, UPDATE_ABORTED, BACKROLL_ABORTED
}